### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by anartoast** [zidaneho/SamiraMod#3]
Hey!!!! Actually a great port from League! I would like to share my opnions on the character and you are the one that categorizes some of the comments as "issues", anyway, going on:

1- Dashing and pressing m1 locks you in a animation wich can get you squashed by monsters like crabs or elden lemurians. Getting attack speed nor actual speed doesn't seems to change the animation speed, and that feels a bit weird when you are flying through the stages, incorages not to do it.

2 - The mobility is too much!! I wont deny that it's the primary hook in the earlier stages and still kinda is on the later ones but it doesnt balances out the things you need to do to get all that mobility, wich is literally pressing a button, later pressing m1 first so you can do enough damage to kill tankier enemies. But i think balancing that would be harder as it's a pillar of a ability i guess. Hooking up to another thing;
The R does way too much damage in a long time, 3 secs is a lot when you are surrounded by ever spawning hordes of mending bettles, wich are of course very treatening. I normaly play using sacrifice remix wich spawns nonstop enemies so i was, most of the time, killing everything with no items. I think making it compressed and deal less damage would be a good fix for the moment? But i'm no pro eclipse 8 player, so i dont have much of a clue of damage numbers and enemies health pools.

3 - You can't chain use the abilities! Or i'm just dumb. I know you can use shift + m1, but it has a some sort of delay to use shift m2 or any other skill with R, wich kinda breaks the "immersion" of a combo character Samira is, or her alias "Dante Devil May Cry (Female)".

4 - Maybe you can split some of the skills as they kinda have a lot of text? I know it's a port of League and they have Senna's passive being longer than Teemo's entire kit, but that doesn't means we can't make it more.... Bite sized....
You can ignore this part if i'm being way too much hyped with this project but as i was playing i was thinking of splitting m1 melee and ranged into three skills:
M1 Shoot like Commando, i think it would be fun to see her jump and do weird movements like in game when she has a lot of atk speed (atleast it was when i played it). Adding a third hit doing something maybe?
M1 Melee like Mercenary. Just swings as basic as it can be, adding crit could make it do something like exploding in a small area, but i don't enjoy much making a character crit based as it's the meta, you are getting crit anyway.
M1 literally like it is right now
.
Shift being split in two skills so it wont do everything by itself;
1º Version: Let it refund cooldown but deal less damage to have a trade off.
2º Version:  Probably lessen the damage aswell, but double down on the atk speed so it would combo really well with the R! And with that it would bring my last point (for now, or fr depending if you like guilhothine me for being annoying);

5 - The style passive is a bit weird? I could barely proc it while changing every other skill to deal damage, but when i just spammed m1 i would consistently get it to S. Maybe i'm just fucking dumb, but that happened.

I'm sorry if it was too much to read, i'm very excited with this character as it's a rare sight to see an modded character that has a god slaying skill with 0 CD or something.
I played only one game, but it was a lenghty one, and, died to Mithrix cause i'm bad lmao.
 
 Hope i didn't annoyed you with all this wall of text!! Looking foward for a response of you :) Best wishes within the modding scene.

**Comment by zidaneho** [comment]
Thanks for the feedback! Your thoughts are always invaluable.

1: I will make the dash attack instantaneous, so that you will be able to move freely after your dash.

2: the dash’s distance is scaled off of movement speed; I will disable this effect to try it out. About the ultimate: I left out a hidden effect that will increase the duration of the ultimate when an enemy was killed. Perhaps I will split this effect into a different ability. I feel like this is why your ultimates are much longer.

3: I will try to implement this change in, but right now I have no clue on how to do it.

4:I like the ideas of different playstyles; I will add the additional abilities based on your feedback.

5:I think you misread the m1 ability. Every 5 uses, there will be a unique attack that counts for an additional stack. I made this change to accomodate for samira’s lack of abilities (I felt that extraskillslots is not necessary)

Again, thanks for the feedback. I would love to make these changes, but I will not be available for some time. I will be back to updates in a 2 weeks.

**Comment by anartoast** [comment]
Ay i didn't expected for you to be so quick responding, thanks!
Some clarifications:
When i say that she has too much mobility early i meant that she dashes too much without much input. As Mercenary, you need to use your expose debuff in a way that makes you *feel* like you have no cd, wich is one of the reasons hes so good at dealing with big groups. In this line of thought, Samira feel like exposeless Merc but also is great at dealing with single target as the ultimate deals so much damage.
It's good to see that you liked the extra skills thing!! I love playing different styles of the same character, i usually download a lot of skills mods to test them out.
I actually misread the m1, that went tottaly out of my orbit, thanks for telling! About the extraskillslots, it's good that you didnt put it, because i, myself, hate this mod, because it reminds me of extra busted characters that has no right to be, wich stops being fun at like 20 min of run.
I'm glad you liked the feedback, sorry if my english is not the usual, i try my best to be objective as i'm not native :) I'll wait the two weeks! Good luck on what you'll be doing and/or good rest.

**Comment by anartoast** [comment]
Hey!! Patch day and i found a issue, sadly. It seems that the wild rush cd is not getting reset?

**Comment by zidaneho** [comment]
hello, thanks for the feedback. about your first issue, i have fixed that; it slipped out of my mind while i was testing the other ability. For the second, I'll probably readd the invincibility to the dash. It's just the high velocity that is causing the fall damage probably. Gonna push this change in a couple of mins

**Comment by anartoast** [comment]
thanks! it's funny how fall damage works on this game. keep up the good work :)

**Comment by anartoast** [comment]
Hey, coming for another round!
I'm still bonking my head on the ground usind wild rush LMAO. Also please add an option to _lower_ the frequency of voice lines please, Dante's voicelines are somewhat ok, buy Samira's are ear hurting :(

**Comment by anartoast** [comment]
Hello! Coming back to Samira, and, playing Dante, he yells TOO loudly. I didn't found any sliders options to lower them so im here.
To add on the volume, it's impossible for me to lower the game volume cause im using a conplicated jank using Parsec.

**Comment by zidaneho** [comment]
ok, i'll see what i can do. I'll look into adding some options within the menu for sfx and vfx so you can adjust it yourself.

**Comment by zidaneho** [comment]
alright, I looked into Risk of Options and have now added volume settings for sfx and voice lines. I hope this solves your issue; I will be uploading this new update in a minute.
