### ISSUE TITLE
Mod not loading

### ISSUE THREAD

**Issue by LunarRuby** [zidaneho/SamiraMod#4]
Hey! I'm having an issue where the mod isn't being loaded, I check the console and I dont see it, all of the libraries load but not Samira, I have a similar problem with another mod too so it might be a reoccouring thing, I would hope there is a remedy for this?
![image_2024-08-30_231810585](https://github.com/user-attachments/assets/58729cec-fd96-4c3c-9ce3-540827af4c43)

**Comment by PaNFiLoVeTs** [comment]
Hi. The author of the mod forgot to put the dll file in the launcher - this is the main file of the mod, thanks to which everything happens, so the mod does not run
You can download this file from here: https://github.com/zidaneho/SamiraMod/tree/main/Build/plugins
and put it in the folder with the mod

**Comment by zidaneho** [comment]
Just checked the zip, and i think i misclicked the readme file instead of the plugins file. really sorry about that
