### ISSUE TITLE
Samira/Dante audio bug in multiplayer

### ISSUE THREAD

**Issue by Harridas** [zidaneho/SamiraMod#6]
Samira/Dante's audio, both sound effects and voice lines seem to play at full volume across the entire stage. It's very annoying in multiplayer.

**Comment by zidaneho** [comment]
Thanks for the feedback. I am going to push all the sounds to be client side so it won't be annoying. When I figure out how to diminish the sound by distance, maybe I'll add it back. These updates will be pushed in a couple of minutes.

**Comment by Harridas** [comment]
Thank you :)
