### ISSUE TITLE
Survivor Mannequin

### ISSUE THREAD

**Issue by anartoast** [zidaneho/SamiraMod#8]
Hey! I was hesitating to open this issue because it's not really a issue that causes any harm, gameplay wise but i figured i should be letting you know about it.
This error appeared on my log too, but, when i reimported my pack it didn't showed up anymore, until i was helping a person in tech support in modcord.

The exact error is: SamiraMod.Survivors.Samira.SamiraSurvivor.SurvivorMannequinSlotController_OnApplyLoadoutToMannequinInstance (On.RoR2.SurvivorMannequins.SurvivorMannequinSlotController+orig_ApplyLoadoutToMannequinInstance orig, RoR2.SurvivorMannequins.SurvivorMannequinSlotController self) (at <b5d0673bab0745fb812a09d63d151904>:IL_0030)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.SurvivorMannequins.SurvivorMannequinSlotController::ApplyLoadoutToMannequinInstance>?83744148(RoR2.SurvivorMannequins.SurvivorMannequinSlotController)
RoR2.SurvivorMannequins.SurvivorMannequinSlotController.Update () (at <a149dbd7438a4e73b97d6600b3a2bbd4>:IL_0069)

I don't exactly grasp what is this related for. My only thought is something related of the way you made the dante skin, perhaps?
I would contact you on discord but for some reason i can't find you there. Anyway, keep up the good work! [(Also im linking a person that reviewed your mod, because they have like 4 subscribers and i think it's pretty cool)](https://www.youtube.com/watch?v=EAnCacgCn2c)

[dontforgetthisone.log](https://github.com/user-attachments/files/17605168/dontforgetthisone.log)
dont mind the log's name :)

**Comment by zidaneho** [comment]
hey, thanks for the feedback again. I'm assuming that this error occurs when you launch the character selection screen, or when you swap skins? I'm trying to reproduce the error but I'm not getting any. Just in case, I'm gonna fix the error by adding more null checks. Hope this will fix it.

I also saw that mod review, and I think its great. I was really hoping on developing another mod, but college has been killing all my time recently. Anyways, thanks for the feedback; I will be pushing these changes.

**Comment by anartoast** [comment]
The same person said that Samira stopped showing altogether with the new update so i am not sure what is going on here as i can't verify what would the problem be myself due to not having access to a computer until next week.
If it works fine in your end i'd bet it has to do with old configs on their end.

**Comment by zidaneho** [comment]
Sorry, I've released 1.5.1 with no asset bundle or soundbank, so thats why its probably not showing up. I've already released a new version this morning because of another user. But if that's not the issue, I've tested and downloaded my zip and refreshed my config. Everything works fine for me.

**Comment by anartoast** [comment]
That's probably it then, thank you.
