### ISSUE TITLE
Mod incorrectly uploaded to thunderstore

### ISSUE THREAD

**Issue by ByteOfRamen** [zidaneho/SamiraMod#9]
The mod was not correctly uploaded to thunderstore for 1.5.1 update. 

1.5.0 Size: 22.5MB
1.5.1 Size: ~200KB

The only thing included in the mod download is the .dll, manifest.json, readme, and icon.png.

**Comment by zidaneho** [comment]
really sorry about that, just uploaded the correct version this time.
